from django.core.exceptions import ValidationError


def id_card_validation(value):
    pass
